### model
model_name_or_path: /netcache/huggingface/Qwen2.5-7B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8

### dataset
dataset: medical_ner_5w_v1_train
template: default
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16
# train_on_prompt: true

### output
output_dir: saves/qwen2.5-7B-v1-lora-1e-5
logging_steps: 10
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
load_best_model_at_end: true
eval_dataset: medical_ner_5w_v1_valid

### eval
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 20
